name: Build & deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build with vuepress
      run: |
        npm ci
        npm run build
    - name: Upload dist/
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: .vuepress/dist
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Download dist/
      uses: actions/download-artifact@v1
      with:
        name: dist
    - run: npm install -g firebase-tools
    - run: firebase -v
